name: "Comment on PR"
inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  pr-message:
    description: "Comment to post on PR"
    required: true
runs:
  using: "node12"
  main: "lib/main.js"
