name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: henrymunro/comment-on-pr-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: Hey look it worked!

      - name: "npm ci"
        run: npm ci

      - name: "build"
        run: npm run build

      - name: "check for uncommitted changes"
        # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
        run: |
          git diff --exit-code --stat -- . ':!node_modules' \
          || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
                   "and check in all changes" \
              && exit 1)
